#!/bin/bash
export MISE_RUBY_SETUP_SHIMS=1

if [ "$1" = "--version" ]; then
  echo "1.0.0"
  exit 0
fi

nohup /opt/cursor.appimage --enable-features=UseOzonePlatform --ozone-platform=wayland "$@" >/dev/null 2>&1 &
