export CONFIG_PATH=/opt/dev/config/luismendoza/dotfiles-master

# if system is mac load mac specific zshrc
if [[ "$OSTYPE" == "darwin"* ]]; then
  source "$CONFIG_PATH/zsh/zshrc.mac"
fi

# if system is linux load linux specific zshrc
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  source "$CONFIG_PATH/zsh/zshrc.linux"
fi

# Load aliases
source "$CONFIG_PATH/zsh/zshrc.alias"
